name: Publish Extension

on:
  push:
    paths:
      - 'dist/**'
      - 'publish.py'
    branches:
      - main
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        env:
          MICROSOFT_EDGE_STORE_CLIENT_ID: ${{ secrets.MICROSOFT_EDGE_STORE_CLIENT_ID }}
          MICROSOFT_EDGE_STORE_SECRET: ${{ secrets.MICROSOFT_EDGE_STORE_SECRET }}
          MICROSOFT_EDGE_STORE_PRODUCT_ID: ${{ secrets.MICROSOFT_EDGE_STORE_PRODUCT_ID }}

        run: python publish.py

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout logs
          git add .
          git commit -m "Update logs"
          
          git push origin HEAD:refs/heads/logs

