name: Publish Extension

on:
  push:
    paths:
      - 'dist/**'
      - 'publish.py'
    branches:
      - main
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update script
        env:
          MICROSOFT_EDGE_STORE_CLIENT_ID: ${{ secrets.MICROSOFT_EDGE_STORE_CLIENT_ID }}
          MICROSOFT_EDGE_STORE_SECRET: ${{ secrets.MICROSOFT_EDGE_STORE_SECRET }}
          MICROSOFT_EDGE_STORE_PRODUCT_ID: ${{ secrets.MICROSOFT_EDGE_STORE_PRODUCT_ID }}

        run: python publish.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add logs/update_file.log
          git commit -m 'Update logs'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
